name: storage_access
description: correct saving/loading files as strings, used to abstract opening and closing files with correct path. All you need to do is provide same filename.
version: 0.0.7
license: LGPL v2/v3
homepage: https://github.com/bgoncharuck/storage_access

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.3.0
  path_provider: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
